Implements error response
darwinia-network/shadow pull request #116
Opened 2020-11-06 17:24 UTC by clearloop

## Desc

Replace the default response with error messages

2020-11-13 04:08 UTC, HackFisher commented
@wuminzhe Will need a companion PR for bridger to handle the new web result (error handling), would you please help provide one, thanks.

2020-11-27 06:33 UTC, wuminzhe approved these changes

2020-11-27 09:23 UTC, HackFisher requested changes

2020-11-27 09:23 UTC, HackFisher commented on src/api/ethereum/helper.rs
> +pub fn mmr_root(block: u64, shared: &ShadowShared) -> WebResult<String> {
```suggestion
pub fn parent_mmr_root(block: u64, shared: &ShadowShared) -> WebResult<String> {
```

2020-11-27 09:23 UTC, HackFisher commented on src/api/ethereum/helper.rs
> +/// Get mmr_root string with web response
```suggestion
/// Get parent_mmr_root string with web response
```

2020-11-27 09:28 UTC, HackFisher requested changes

2020-11-27 09:28 UTC, HackFisher commented on src/api/ethereum/mmr_leaf.rs
> +        .unwrap_or([0; 32]);
Using match to return approximate result

2020-11-27 12:42 UTC, HackFisher approved these changes

2020-11-27 12:42 UTC, merged