limit DAG file size & optimize logs
darwinia-network/shadow pull request #122
Opened 2020-12-04 02:28 UTC by xiaoch05

2020-12-04 06:31 UTC, HackFisher requested changes

2020-12-04 06:31 UTC, HackFisher commented on pkg/ethashproof/cache.go
> +    log.Assert(err)
format

2020-12-04 06:31 UTC, HackFisher commented on pkg/ethashproof/dag_merkle_root.go
> +    log.Info("Make the dag epoch %v", epoch)
format

2020-12-04 10:54 UTC, HackFisher commented
@xiaoch05 I request some changes regarding format.

@wuminzhe Please help review this pull request.

2020-12-04 11:56 UTC, xiaoch05 commented on pkg/ethashproof/cache.go
> +    log.Assert(err)
ok, fix it.

2020-12-07 02:42 UTC, wuminzhe approved these changes

2020-12-07 06:23 UTC, HackFisher approved these changes

2020-12-07 06:23 UTC, merged