Supports multiple ethereum API
darwinia-network/shadow pull request #95
Opened 2020-10-30 07:36 UTC by clearloop

## Desc

Migrates the new usage of primitives

2020-10-30 08:47 UTC, clearloop commented on src/mmr/runner.rs
> +                thread::spawn(move || Self::epoch((ptr + 15000) as u64))
Pre-run `epoch` before 15000 blocks

2020-10-30 09:50 UTC, clearloop commented
https://github.com/darwinia-network/shadow/blob/bd7cbcfe1d4388426c440d9f49b07e8c93407988/src/api/ethereum/ffi.rs#L44

Got a problem parsing Ethereum API using FFI on the Golang side.

2020-10-30 10:28 UTC, clearloop commented on src/api/ethereum/ffi.rs
> -
This rust pointer will be dropped by the garbage collection mechanism of golang

2020-11-02 02:35 UTC, HackFisher approved these changes

2020-11-02 03:24 UTC, HackFisher requested changes
Need further checking and testing

2020-11-02 11:45 UTC, HackFisher approved these changes

2020-11-02 11:45 UTC, merged

2020-11-03 04:54 UTC, HackFisher commented on pkg/shadow/eth/receipt.go
>  	pointer := &dto.RequestResult{}
Could API be start with ```"http://```